In [ ]:
 Создайте квадратный двумерный массив 4 на 4, заполненный единицами.
    Преобразуйте его в массив, заполненный пятерками. 
    Измените форму массива на 2 на 8.
    Выведите получившийся массив. 
    Сохраните файл Jupyter notebook с названием «Задание 4_1.ipynb» и загрузите его в созданный репозиторий.

In [2]:
import numpy
import pandas
import matplotlib.pyplot
t=(4,4)
a=numpy.ones(t)
print(a)
a*=5
print(a)
a = a.reshape((2, 8))
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5.]]
